### ISSUE TITLE
Error in VOC Evaluation script

### ISSUE THREAD

**Issue by sainivedh** [NVlabs/AL-MDN#4]
`Traceback (most recent call last):
  File "eval_voc.py", line 440, in <module>
    thresh=args.confidence_threshold)
  File "eval_voc.py", line 384, in test_net
    detections = net(x).data
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/MDN/ssd_gmm.py", line 296, in forward
    conf_pi_4.view(conf_var_4.size(0), -1, 1)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/function.py", line 151, in __call__
    "Legacy autograd function with non-static forward method is deprecated. "
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)`

Pytorch Version - 1.9.0

**Comment by jwchoi384** [comment]
Hello,
As mentioned in the README, we tested our code with Pytorch 1.1.
Please test using Pytorch 1.1 as it may not work with other Pytorch versions.
